[tool.poetry]
name = "sample-annotator"
version = "0.1.0"
description = "NMDC Sample Annotator"
authors = ["Chris Mungall <cjmungall@lbl.gov>"]
license = "CC0 1.0 Universal"

[tool.poetry.dependencies]
Sphinx = "^4.4.0"
bioregistry = "^0.4.59"
click-log = "^0.4.0"
diskcache = "^5.4.0"
funowl = "^0.1.11"
git-root = "^0.1"
googlemaps = "^4.6.0"
linkml = "^1.1.18"
nmdc-schema = { version = "7.0.0", allow-prereleases = false }
pandas = "^1.4.1"
python = "^3.9"
quantulum3 = "^0.7.10"
recommonmark = "^0.7.1"
sphinx-rtd-theme = "^1.0.0"
uvicorn = "^0.17.4"
validators = "^0.20.0"
python-dotenv = "^0.20.0"
pendulum = "^2.1.2"
# lat-lon-parser = "^1.3.0"
# LatLon23 = "^1.0.7"


[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
black = "^22.1.0"
pytest = "^7.0.1"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
annotate-sample = "sample_annotator.sample_annotator:cli"
sqlite_client_cli = "sample_annotator.clients.biosample_sqlite_client:cli"
rel_to_oxygen_example = "sample_annotator.rel_to_oxygen_example:cli"
biosample_instantiator_plus = "sample_annotator.clients.nmdc.biosample_instantiator_plus:cli"
add_depth2 = "sample_annotator.clients.nmdc.add_depth2:cli"

