[tool.poetry]
name = "sample-annotator"
version = "0.1.0"
description = "NMDC Sample Annotator"
authors = ["Chris Mungall <cjmungall@lbl.gov>"]
license = "CC0 1.0 Universal"

[tool.poetry.dependencies]
Sphinx = "^8.0"
bioregistry = "^0.4.59"
click-log = "^0.4"
diskcache = "^5.6"
funowl = "^0.2"
git-root = "^0.1"
googlemaps = "^4.6.0"
linkml = "^1.7"
nmdc-schema = "^11.0"
pandas = "^2.2"
numpy = "^2.2"
python = "^3.10"
quantulum3 = "^0.9"
recommonmark = "^0.7.1"
sphinx-rtd-theme = "3.0"
uvicorn = "^0.30"
python-dotenv = "^1.0"
deptry = "^0.21.2"


[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
black = "^22.1.0"
pytest = "^7.0.1"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
annotate-sample = "sample_annotator.sample_annotator:cli"
sqlite_client_cli = "sample_annotator.clients.biosample_sqlite_client:cli"
rel_to_oxygen_example = "sample_annotator.rel_to_oxygen_example:cli"
