[tool.poetry]
name = "sample-annotator"
version = "0.1.0"
description = "NMDC Sample Annotator"
authors = ["Chris Mungall <cjmungall@lbl.gov>"]
license = "CC0 1.0 Universal"

[tool.poetry.dependencies]
Sphinx = "^4.4.0"
bioregistry = "^0.4.59"
click-log = "^0.3.2"
diskcache = "^5.4.0"
funowl = "^0.1.11"
git-root = "^0.1"
googlemaps = "^4.6.0"
linkml = "^1.1.18"
nmdc-schema = "^2.0.0"
pandas = "^1.4.1"
python = "^3.9"
quantulum3 = "^0.7.10"
recommonmark = "^0.7.1"
sphinx-rtd-theme = "^1.0.0"
uvicorn = "^0.17.4"
bio = "^1.5.5"
xmltodict = "^0.13.0"


[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
black = "^22.1.0"
pytest = "^7.0.1"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
annotate-sample = "sample_annotator.sample_annotator:cli"
sqlite_client_cli = "sample_annotator.clients.biosample_sqlite_client:cli"
rel_to_oxygen_example = "sample_annotator.rel_to_oxygen_example:cli"
ncbi_client = "sample_annotator.clients.ncbi_client:cli"
