[tool.poetry]
name = "sample-annotator"
version = "0.1.0"
description = "NMDC Sample Annotator"
authors = ["Chris Mungall <cjmungall@lbl.gov>"]
license = "CC0 1.0 Universal"

[tool.poetry.dependencies]
oaklib = "*"
Sphinx = "^4.4.0"
#bioregistry = "^0.4.59"
bioregistry = "*"
click-log = "^0.3.2"
diskcache = "^5.4.0"
funowl = "^0.1.11"
git-root = "^0.1"
googlemaps = "^4.6.0"
linkml = "^1.4.11"
nmdc-schema = "^7.0.0"
pandas = "^1.4.1"
python = "^3.9"
quantulum3 = "^0.7.11"
recommonmark = "^0.7.1"
sphinx-rtd-theme = "^1.0.0"
uvicorn = "^0.17.4"
python-dotenv = "^0.21.1"


[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
black = "^22.1.0"
pytest = "^7.0.1"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
annotate-sample = "sample_annotator.sample_annotator:cli"
sqlite_client_cli = "sample_annotator.clients.biosample_sqlite_client:cli"
rel_to_oxygen_example = "sample_annotator.rel_to_oxygen_example:cli"
oak-tree-to-pv-list = "sample_annotator.clients.neon.oak_tree_to_pv_list:main"
