name: Check Pull Request

# Controls when the action will run. Triggers the workflow on pull requests.
on:
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: trigger-check-pull-request
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.15

      # Install pandoc
      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.0


      - name: Poetry install deps
        run: poetry install

      # tests are governed by the Makefile
      - name: Make Test
        run: |
          make test
